apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: logging
data:
  filebeat.yml: |
    filebeat.inputs:
      - type: log
        enabled: true
        paths:
          - /ollama/ollama.log
          - /maclogs/system.log

    output.elasticsearch:
      hosts: ["http://opensearch.logging.svc.cluster.local:9200"]
      protocol: "http"
      username: ""
      password: ""
      ssl.verification_mode: none
