apiVersion: v1
kind: Service
metadata:
  name: opensearch
  namespace: logging
spec:
  selector:
    app: opensearch
  ports:
    - port: 9200
      targetPort: 9200
      nodePort: 30200
  type: NodePort
