apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: opensearch
  namespace: logging
spec:
  serviceName: opensearch
  replicas: 1
  selector:
    matchLabels:
      app: opensearch
  template:
    metadata:
      labels:
        app: opensearch
    spec:
      containers:
        - name: opensearch
          image: opensearchproject/opensearch:2.13.0
          ports:
            - containerPort: 9200
              name: rest
            - containerPort: 9600
              name: metrics
          env:
          env:
            - name: discovery.type
              value: "single-node"
            - name: plugins.security.disabled
              value: "true"
            - name: OPENSEARCH_JAVA_OPTS
              value: "-Xms512m -Xmx512m"
            - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
              value: "N3mera9e1234#"
          volumeMounts:
            - name: opensearch-data
              mountPath: /usr/share/opensearch/data
  volumeClaimTemplates:
    - metadata:
        name: opensearch-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
